name: Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: treeform/setup-nim-action@v6
      - run: nimby install -g
      - run: nimby install -g windy
      - name: Install Vulkan SDK
        run: winget install -e --id KhronosGroup.VulkanSDK --accept-package-agreements --accept-source-agreements
      - run: nim check src/vk14.nim
      - run: nim r tests/tests.nim
      - run: nim r examples/compile_shaders.nim
      - run: nim c examples/basic_screen.nim
      - run: nim c examples/basic_triangle.nim
      - run: nim c examples/basic_quad.nim
      - run: nim c examples/basic_cube.nim
      - run: nim c examples/viewer_obj.nim
      - run: nim c examples/sprite_sheet.nim
